### ISSUE TITLE
Can not find

### ISSUE THREAD

**Issue by ShofB** [dhuber81/huaba#1]
I downloaded this using the plugin manager but it does not show up in my plugins.  Any ideas?  I'm on a W10 system.

**Comment by dhuber81** [comment]
i cannot replicate this problem. Does the search function work for eq3?

**Comment by ShofB** [comment]
I just installed everything on anther computer and it's all working.  Thanks for looking into it

Shof B

My Web Site
http://www.l-and-l.net<http://www.l-and-l.net/>

Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg
________________________________
